spring:
  datasource:
    url: jdbc:sqlserver://192.168.10.22;databaseName=sample_springboot_db
    username: sa
    password: ada022!
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    
    
server:
  port: 3000